language: bash
services: docker

branches:
  only:
    - master

env:
  - ARCH=x86_64
  - ARCH=armhf

install:
  - git clone https://github.com/lafin/bof.git ${ARCH}/

before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - sed -ie "s/FROM lafin\/alpine-golang:platform/FROM lafin\/alpine-golang:${ARCH}\-1.7.5/" ${ARCH}/Dockerfile

script:
  - docker build -t lafin/bof:${ARCH} ${ARCH}

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push lafin/bof