language: bash
services: docker
branches:
  only:
    - master
env:
  global:
    - DOCKER_REPO=lafin/bof
  matrix:
    - ARCH=x86_64 GOOS=linux GOARCH=amd64 GOARM=
    - ARCH=armhf GOOS=linux GOARCH=arm GOARM=7
install:
  - git clone https://github.com/lafin/bof.git ${ARCH}/
script:
  - docker build --build-arg GOOS=${GOOS} --build-arg GOARCH=${GOARCH} --build-arg GOARM=${GOARM} --build-arg DOCKER_REPO=${DOCKER_REPO} -f ${ARCH}/Dockerfile.build -t ${DOCKER_REPO}:${ARCH} ${ARCH}
  - docker run --name ${GOARCH} ${DOCKER_REPO}:${ARCH}
  - docker cp ${GOARCH}:/go/src/github.com/${DOCKER_REPO}/${GOARCH} ${ARCH}/${GOARCH}
  - docker build --build-arg GOARCH=${GOARCH} -f ${ARCH}/Dockerfile.prod -t ${DOCKER_REPO}:${ARCH} ${ARCH}
after_success:
    - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push $DOCKER_REPO; fi